services:
  - type: web
    name: bhasyam-portal
    runtime: node
    buildCommand: npm install && npm run build
    rootDir: .
    startCommand: node src/.output/server/index.mjs
    envVars:
      - key: NITRO_PORT
        value: 10000
